apiVersion: v1
kind: ServiceAccount
metadata:
  name: zuul-gateway
  namespace: zuul-security
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT-ID:role/zuul-gateway-role
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: zuul-security
  name: zuul-gateway-role
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["*"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: zuul-gateway-binding
  namespace: zuul-security
subjects:
- kind: ServiceAccount
  name: zuul-gateway
  namespace: zuul-security
roleRef:
  kind: Role
  name: zuul-gateway-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: security-scanner
  namespace: security-scanning
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: security-scanner-role
rules:
- apiGroups: [""]
  resources: ["pods", "replicasets", "deployments"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["security.k8s.io"]
  resources: ["podsecuritypolicies"]
  verbs: ["use"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: security-scanner-binding
subjects:
- kind: ServiceAccount
  name: security-scanner
  namespace: security-scanning
roleRef:
  kind: ClusterRole
  name: security-scanner-role
  apiGroup: rbac.authorization.k8s.io