apiVersion: v1
kind: Service
metadata:
  name: zuul-gateway-stable
  namespace: zuul-security
  labels:
    app: zuul-gateway
    service: stable
spec:
  selector:
    app: zuul-gateway
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: https
    port: 443
    targetPort: 8443
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: zuul-gateway-canary
  namespace: zuul-security
  labels:
    app: zuul-gateway
    service: canary
spec:
  selector:
    app: zuul-gateway
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: https
    port: 443
    targetPort: 8443
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: zuul-gateway
  namespace: zuul-security
  labels:
    app: zuul-gateway
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:region:account:certificate/cert-id"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
spec:
  selector:
    app: zuul-gateway
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: https
    port: 443
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: zuul-gateway-vs
  namespace: zuul-security
spec:
  hosts:
  - zuul-gateway.zuul-security.svc.cluster.local
  - gateway.yourdomain.com
  gateways:
  - zuul-security-gateway
  http:
  - name: primary
    match:
    - headers:
        canary:
          exact: "true"
    route:
    - destination:
        host: zuul-gateway-canary.zuul-security.svc.cluster.local
      weight: 100
  - name: primary
    route:
    - destination:
        host: zuul-gateway-stable.zuul-security.svc.cluster.local
        subset: stable
      weight: 100
    - destination:
        host: zuul-gateway-canary.zuul-security.svc.cluster.local
        subset: canary
      weight: 0
    timeout: 30s
    retries:
      attempts: 3
      perTryTimeout: 10s
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: zuul-gateway-dr
  namespace: zuul-security
spec:
  host: zuul-gateway.zuul-security.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 10
        http2MaxRequests: 100
        maxRequestsPerConnection: 10
        maxRetries: 3
    circuitBreaker:
      consecutiveErrors: 5
      interval: 30s
      baseEjectionTime: 30s
      maxEjectionPercent: 50
  subsets:
  - name: stable
    labels:
      version: stable
    trafficPolicy:
      tls:
        mode: ISTIO_MUTUAL
  - name: canary
    labels:
      version: canary
    trafficPolicy:
      tls:
        mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: zuul-security-gateway
  namespace: zuul-security
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: zuul-gateway-tls
    hosts:
    - gateway.yourdomain.com
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - gateway.yourdomain.com
    tls:
      httpsRedirect: true